### PR TITLE
fork-run/dev-mode fixes

### PR DESCRIPTION
**Pull request by havocp**

### CODE REVIEW

**Comment by havocp** [comment]
well, the scripted test passed once with this I think, but now is failing again. still these changes make it a little easier to see what's happening perhaps.

**Comment by havocp** [comment]
`scripted fork-run/dev-mode` by itself seems to pass, while the full `scripted` seems to fail; so perhaps the problem is leakage between scripted tests or something along those lines... maybe everyone is trying to use localhost:9000 ? just an idea.

**Comment by havocp** [comment]
Yep that was it. the fork-run/dev-mode scripted test is running against the play app launched by another test. About to push a commit that "proves" it.

**Comment by pvlugter** [comment]
So running `scripted` in the root project? The PR validation uses the `runtests` script, which runs the scripted tests for a few projects in turn, like `SBT-Fork-Run-Plugin/scripted`. They could use different ports so that scripted for different projects can run in parallel, but validation should work fine if the fork run scripted tests work in isolation.

**Comment by havocp** [comment]
ah ok. Yeah I was just typing "scripted"

I think the tests pass now if you run in isolation, with this PR applied anyway.

**Comment by corruptmemory** [comment]
Looks ok. The hard-coded timings aren't my favorite. Should look at a better way in the future.

**Comment by pvlugter** [comment]
@jroper's original comment shows why the sleeps are there. Not sure that there would better way to wait than simply let some time pass. The original play-sbt-plugin/dev-mode test may need the longer than 1 second times as well?

**Comment by corruptmemory** [comment]
Sure. What I have in mind is a notification sink from the forked child that defaults to nothing but can be turned on  during tests.

**Comment by jroper** [comment]
With the timings, it's hard - sometimes we wait to ensure that nothing happened.

The concurrency issue with `scripted` we should fix, it can be done with:

``` scala
ScriptedPlugin.scripted <<= ScriptedPlugin.scripted.tag(Tags.Test)
```

because we already have a global concurrency restriction of one for all test tagged tasks.

**Comment by jroper** [comment]
https://github.com/playframework/playframework/pull/3908

**Pull request merged**
